### PR TITLE
[WIP] Refactor trend enum values into class

### PR DESCRIPTION
**Pull request by inverse**

### CODE REVIEW

**Comment by ZENALC** [comment]
This is great, but the only thing is that all strategies that that people may have written will need to be updated after this merges. We may need to need bump up the v slightly and trigger a popup for people to know that their strategies will need to be updated.

**Comment by ZENALC** [comment]
A tool to automatically do this would be awesome, but not sure if we can do it easily.

**Comment by inverse** [comment]
@ZENALC Can you show me where the other strategies that users create are passed in? You mean through them modifying their code locally?

**Comment by inverse** [comment]
Ahh found it!

**Pull request closed without merging**
